### ISSUE TITLE
Plugin won't load (Fatal error)

### ISSUE THREAD

**Issue by m4rc0d1** [JoeSz/Exopite-Multifilter-Multi-Sorter-WordPress-Plugin#2]
The plugin doesn't load because of an error in file public/class-exopite-multifilter-public.php at line 289

The issue is a misplaced parenthesis. The line is:

 if ( ! empty( $args['video'] && ! empty( $video_url ) ) ) {

but should be:

 if ( ! empty( $args['video'] ) && ! empty( $video_url ) ) {

**Comment by JoeSz** [comment]
Thank you! I fixed it.
