### ISSUE TITLE
This isn't working.

### ISSUE THREAD

**Issue by Moderndayfreak** [JoeSz/Exopite-Multifilter-Multi-Sorter-WordPress-Plugin#4]
Latest version on Wordpress 5.2.2 

Its not working. I thoroughly read the documentation but nothing. Eventually the plugin stopped showing up in the wordpress plugin page. I uploaded the: exopite-multifilter folder from the downloaded zip file. Currently looking at your code.

**Comment by Moderndayfreak** [comment]
Yea.. Got it to work but after awhile the plugin crashes and gets uninstall.

**Comment by Moderndayfreak** [comment]
Yo Joe.... You still alive? Sent multiple emails and nothing...

**Comment by JoeSz** [comment]
I did sent you two emails. I'm on vacation at the moment. I will be back mid. September.
Please check your SPAM folder too.

**Comment by Moderndayfreak** [comment]
Oh ok….So no support til Mid Sept? Your plugin is what we’re looking for but after a while it just disappears from the plugin dashboard and the short code stops working.

I’ll check my spam box.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
Well there is no support by default ;) but I do what I can. No, unfortunately, I have definitely no time until mid. Sept.

**Comment by JoeSz** [comment]
But you still can write your list, what is the problem exactly and what do you like to change or add.

**Comment by JoeSz** [comment]
You can post it here or send me an email.

**Comment by JoeSz** [comment]
and if you have any idea what is the problem by you, please do not hesitate to share ;)

**Comment by Moderndayfreak** [comment]
So after installing the plugin and adding the short code to a page within 10 minutes the plugin stops working. Really weird. I was up late last night working on it and the css and when I encountered this problem several times I would delete the plugin from the directory and re-upload it and then activated it. There was no other way to make it work. All is well then it happens again. I didn’t realize that you were on vacation and now I understand why it was taking awhile to respond back. Your plugin is exactly what we need so with this being said… We don’t have any plugins that is conflicting with it. I already ran a test on that. Thanks Joe for everything.


JoJo



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Moderndayfreak** [comment]
When using this short code the tags do not show up. I know your on holiday but we would like to get this out of the way asap sir. Thanks bro



[cid:image001.jpg@01D5625C.A9D6FD50]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Moderndayfreak** [comment]
We just want to make it look like this page:

https://flowproject.la/search-pro/


with the tag clouds being multi selected.

https://flowproject.la/new-archives/  (your short codes)

We just need to be pointed in the right diorection.


Thanks!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Moderndayfreak** [comment]
It just crashed on us again. It works then after 5 minutes it just stops working. The folder is still in the plugins directory but it no longer shows up on the wp plugins page.

Why????

Azalea

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
I created a test system, with the WordPress 5.2.3 (I checked it in 5.2.2 too) with a "twentynineteen" and no other plugins and PHP 7.3. I have no problems. No crashing at all. The plugin also running in my website, also without problem. So I guess, the problem lies by you. To investigate further, I need a copy from your WordPress. If you want to do this, please make a duplicator snapshot and send to me. (Please remove all sensitive data before!)

**Comment by Moderndayfreak** [comment]
I can give you access to the site and you can see exactly what I am talking about.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
It may not enough, I need to see the PHP code too to test.

**Comment by Moderndayfreak** [comment]
Ok I will give you access to the site as admin and ftp.. I’ll set it up and will send you the info within the hour. Joe your awesome. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
Please do not :) I need a local environment to test, without causing any problem in a live site.

**Comment by JoeSz** [comment]
Unfortunately, I have not received any access data yet. Only for info.

**Comment by Moderndayfreak** [comment]
Username: joe
Password: joecool1

https://flowproject.la/wp-admin


The page I was using for your plugin is: new archives. You will see your shortcode in it sir.
If you re-upload and re-install your plugin, the shortcode will work BUT within 5 minutes it will stop working. The multi selectable tags won’t show either.


Thank you so much Joe


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Moderndayfreak** [comment]
Sftp info:

Username: flowproject
Password: Flow13!

Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
I have deleted from GitHub the access infos, because here ALL can see it.

**Comment by JoeSz** [comment]
YOu have should send this to me per email ;)

**Comment by Moderndayfreak** [comment]
What is your email???

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
I have a contact from on my website, please send an email and I can answer. https://www.joeszalai.org

**Comment by JoeSz** [comment]
I made a local copy. I did not have any issue yet. Your shortcode is wrong. It should be:

[exopite-multifilter multi_selectable="false" include_taxonomies="post_tag" taxonomy_terms__in="post_tag(a-story|current-events)" posts_per_page="30" posts_per_row="6" display_filter="true" display_title="true" pagination="readmore" effect="none" except_lenght="0" display_filter_title="false"]

**Comment by JoeSz** [comment]
I'm doing further tests.

**Comment by JoeSz** [comment]
"taxonomies_terms" is deprecated, use include_taxonomies (I know, I did not correctly updated the infos about this). If you want to display only this two terms, then you need taxonomy_terms__in="post_tag(a-story|current-events)" In your case the taxonomy is "post_tag" which is the "tags" in WordPress and the terms are "current-events, a-story".

**Comment by JoeSz** [comment]
What do you do exactly before crash the plugin, what do you do right before? Use some other plugin, save somethnig, or use the filter?

**Comment by Moderndayfreak** [comment]
Nothing…


I install your plugin and copy the shortcode in the page. It works then about 5 minutes later it stops working. I disable all the plugins and repeat the same thing but still the same thing. Once it stops working then the shortcode only appears on the page. Not the actual grid, etc.

Thanks bro



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
I still don't have any problems. Localhost ist the same as live site, so something is wrong with a host. Which PHP/SQL versions do you use?

**Comment by Moderndayfreak** [comment]
Its 7.3 and the latest version of WordPress. There is nothing wrong with our hosts. This is why I wanted you to login to see exactly what I am talking about.
Your plugin is not working for us… I also load it on another server on another site and its not working there either.




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JoeSz** [comment]
My last idea, the "plugin update checker" was an older version. I have updated. If you wish to try, please update the plugin from here.

**Comment by JoeSz** [comment]
or you can also comment out from the plugin main php file.

**Comment by JoeSz** [comment]
Close issue due lack of information.
