### ISSUE TITLE
No valid plugins were found

### ISSUE THREAD

**Issue by sudeep-patil** [JoeSz/Exopite-Multifilter-Multi-Sorter-WordPress-Plugin#5]
when i uploaded plugins it shows The package could not be installed. No valid plugins were found.

**Comment by JoeSz** [comment]
Do you mean update with the update function?

**Comment by sudeep-patil** [comment]
no when i trying to install it it showing no valid plugin found..

**Comment by JoeSz** [comment]
I tested it, I do not have a problem to install it. Maybe you upload a zip file and the plugin folder is inside an other folder? Or how did you try to install it?

**Comment by JoeSz** [comment]
Closing issue due to lack of response.
