### ISSUE TITLE
Select/radio-buttons option?

### ISSUE THREAD

**Issue by Jeka1beks** [JoeSz/Exopite-Multifilter-Multi-Sorter-WordPress-Plugin#7]
Hi, Joe!

Great job developing this plugin. Keep it up!
I have three custom taxonomies. Tell me, can I somehow use single-choice filters separately from each other?
Please tell me how to implement something like the following:

1st taxonomy - Color (red OR green OR blue)
2nd taxonomy - Shape (square OR triangle OR circle)
3rd taxonomy - Size (small OR medium OR large)
So it will be three groups of select-box or radio-buttons or something.

Can you tell in which direction to think?

**Comment by JoeSz** [comment]
Hi,
no, unfortunately the plugin can not do this. Single choose will allow choose one and multiple will allow multiple from all three taxonomies.
Whats you want is a kind of grouping. It is possible to do it, but you need to extend the JavaScirpt.
I do not need to use the plugin like this, so -in the moment- I will not implement it.
But, if you want to do it, please do, and send me a pull request.
